dashdota/Dashboard/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using ModelsLibrary;
using TableStorage;
using TableStorage.Models;
using Dashboard.Models;
using Dashboard.Helpers;

namespace Dashboard.Controllers
{
    public class GameController : Controller
    {
        /// <summary>
        /// AJAX handler that returns a list of game state objects in Json form,
        /// one for each team member.
        /// </summary>
        /// <param name="id">steam Id</param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> GetGameState(string id)
        {
            // Create an empty list of game states.
            List<GameStateEntity> gameStates = new List<GameStateEntity>();

            // Return immediately if Id is empty.
            if (string.IsNullOrEmpty(id))
            {
                return new JsonNetResult(new GameStateModel());
            }

            // Set valid time range to 10 seconds in the past. Otherwise,
            // the game state is considered stale and won't be queried.
            var rowKeyLower = (DateTime.MaxValue.Ticks - DateTime.UtcNow.Ticks).ToString();
            var rowKeyUpper = (DateTime.MaxValue.Ticks - (DateTime.UtcNow.Ticks - TimeSpan.FromSeconds(10).Ticks)).ToString();

            // Get the most recent game state from the steam Id passed in.
            var gameState = await GameStateTable.GetLastGameStateAsync(id, rowKeyLower, rowKeyUpper);

            // If game state exists and valid for the current steam Id.
            if (gameState != null)
            {
                // Add the current game state to the list.
                gameStates.Add(gameState);

                // Use the current game state's MatchId and Team name to see if any other
                // players are sending game sense telemetry within the same team.
                var team = await TeamTable.GetTeamMembersAsync(gameState.MatchId, gameState.Team);

                foreach (var member in team)
                {
                    // Get each member's steam Id from the RowKey property.
                    var steamId = member.RowKey;

                    // Skip the case when we're querying ourselves twice.
                    if (steamId == id)
                    {
                        continue;
                    }

                    // Get the most recent game state for each member found.
                    var memberGameState = await GameStateTable.GetLastGameStateAsync(steamId, rowKeyLower, rowKeyUpper);

                    if (memberGameState != null)
                    {
                        // If game state exists and valid, add it to the list.
                        gameStates.Add(memberGameState);
                    }
                }
            }

            // Order the complete list of game states by networth.
            gameStates = gameStates.OrderByDescending(o => o.Networth).ToList();

            // Return the game state model in Json format.
            return new JsonNetResult(new GameStateModel(gameStates));
        }

        /// <summary>
        /// Action handler that generates and downloads the game sense integration
        /// configuration file.
        /// </summary>
        /// <param name="id">steam Id</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> DownloadConfig(string id)
        {
            // Check if this user already has an auth token.
            var token = await AuthTokenTable.GetAuthTokenAsync(id);

            if (string.IsNullOrEmpty(token))
            {
                // Generate a new auth token.
                token = KeyGenerator.GetUniqueKey(20);

                // Store the steam Id and auth token.
                await AuthTokenTable.AddEntityAsync(id, token);
            }

            // Generate and download the config file.
            MemoryStream memoryStream = new MemoryStream();
            TextWriter tw = new StreamWriter(memoryStream);

            tw.WriteLine("\"Dota 2 Integration Configuration\"");
            tw.WriteLine("{");
            tw.WriteLine("    \"uri\"           \"http://dashdota-api.azurewebsites.net/api/game\"");
            tw.WriteLine("    \"timeout\"       \"5.0\"");
            tw.WriteLine("    \"buffer\"        \"0.1\"");
            tw.WriteLine("    \"throttle\"      \"0.1\"");
            tw.WriteLine("    \"heartbeat\"     \"5.0\"");
            tw.WriteLine("    \"auth\"");
            tw.WriteLine("    {");
            tw.WriteLine("        \"token\"         \"{0}\"", token);
            tw.WriteLine("    }");
            tw.WriteLine("    \"data\"");
            tw.WriteLine("    {");
            tw.WriteLine("        \"provider\"      \"1\"");
            tw.WriteLine("        \"map\"           \"1\"");
            tw.WriteLine("        \"player\"        \"1\"");
            tw.WriteLine("        \"hero\"          \"1\"");
            tw.WriteLine("        \"abilities\"     \"1\"");
            tw.WriteLine("        \"items\"         \"1\"");
            tw.WriteLine("    }");
            tw.WriteLine("}");
            tw.Flush();
            tw.Close();

            return File(memoryStream.GetBuffer(), "text/plain", "gamestate_integration_dashdota.cfg");
        }
    }
}

dashdota/Dashboard/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using SteamWebAPI2.Interfaces;
using Dashboard.Models;

namespace Dashboard.Controllers
{
    public class HomeController : Controller
    {
        public async Task<ActionResult> Index()
        {
            ApplicationUserManager manager = HttpContext.GetOwinContext().Get<ApplicationUserManager>();

            // Create an empty View Model.
            var viewModel = new DashboardViewModel();

            // Return empty View Model immediately if not logged in. 
            if (!User.Identity.IsAuthenticated)
            {
                return View(viewModel);
            }

            // We are logged in. Get User's external login information.
            var logins = await manager.GetLoginsAsync(User.Identity.GetUserId());

            foreach (var login in logins)
            {
                // Look for the specific login from Steam provider.
                if (login.LoginProvider == "Steam")
                {
                    // Steam Id is the segment with index 3 from Uri.
                    var steamId = new Uri(login.ProviderKey).Segments[3];

                    // Populate the view model with steam Id.
                    viewModel.SteamId = steamId;

                    // TODO: Should really create a "dev" or "admin" user role in ASP.NET user database
                    // and check if the user is assigned to said role. Perhaps someday when I'm not the only
                    // person working on this...
                    viewModel.DeveloperView = (steamId == "76561197983364518" ? true : false);

                    long steamIdL;
                    if (long.TryParse(steamId, out steamIdL))
                    {
                        // Map to the ISteamUser endpoint.
                        var steamInterface = new SteamUser(ConfigurationManager.AppSettings["SteamApiKey"]);

                        // Steam API call to get the player summary.
                        var playerSummary = await steamInterface.GetPlayerSummaryAsync(steamIdL);

                        // Stick the relevant info into the ViewBag for now.
                        // TODO: Prefer to use strongly typed views (models) instead of ViewBags.
                        ViewBag.NickName = playerSummary.Nickname;
                        ViewBag.ProfileUrl = playerSummary.ProfileUrl;
                        ViewBag.AvatarUrl = playerSummary.AvatarMediumUrl;
                    }
                }
            }

            return View(viewModel);
        }
    }
}

dashdota/Dashboard/Views/Home/Index.cshtml
@model Dashboard.Models.DashboardViewModel
@{
    ViewBag.Title = "Dash Dota";
}

<h3>1. Sign in with Steam</h3>

@if (Model.DeveloperView)
{
    <p>Enter steam Id (developer only):</p>
    <div>
        <form id="form" onsubmit="return false;">
            <input type="text" id="userInput" />
            <input type="submit" onclick="SetSteamId();" />
        </form>
    </div> <br />

    <script>
        function SetSteamId() {
            steamId = document.getElementById("userInput").value;
            alert("Steam Id has been changed to: " + steamId);
        }
    </script>
}

<h3>2. Download the config file</h3>

@if (!string.IsNullOrEmpty(Model.SteamId))
{
    using (Html.BeginForm("DownloadConfig", "Game", new { id = Model.SteamId }, FormMethod.Post, new { @target = "_Blank" }))
    {
        <button type="submit" class="btn btn-default">Download</button>
    }
}
<br />

<p>
    Make sure the above file is placed in the location: <br />
    \steamapps\common\dota 2 beta\game\dota\cfg\gamestate_integration\gamestate_integration_dashdota.cfg <br /><br />

    Note: You may have to manually create the "gamestate_integration" folder in the above path. <br />
</p>

<h3>3. Your Networth and Exp will appear below</h3>
<hr />

<div id="networthWidgetArea"></div>

@section Scripts {
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/Scripts/jquery-1.10.2.js")
    @Scripts.Render("~/Scripts/Dashdota/Widgets/AlertWidget.js")
    @Scripts.Render("~/Scripts/Dashdota/Widgets/NetworthBarWidget.js")
    @Scripts.Render("~/Scripts/Dashdota/Widgets/NetworthWidget.js")
    @Scripts.Render("~/Scripts/Dashdota/NetworthScript.js")
    @Scripts.Render("~/Scripts/Dashdota/GameStateScript.js")

<script>
    GetGameStateUrl = "@Url.Action("GetGameState", "Game")";
    BaseImageDirectoryUrl = "@Url.Content("~/Content/Images/")";
    HeroImageDirectoryUrl = "@Url.Content("~/Content/Images/Heroes/")";
    ItemImageDirectoryUrl = "@Url.Content("~/Content/Images/Items/")";
    AlertImageDirectoryUrl = "@Url.Content("~/Content/Images/Alerts/")";
    NetworthImageDirectoryUrl = "@Url.Content("~/Content/Images/Networth/")";

    var steamId = "@(Model.SteamId)";

    const TimeoutLengthMs = 500;

    $.ajaxSetup({
        timeout: 10000
    });

    $(document).ready(function () {
        //Once everything else is loaded, start getting in real time information
        setTimeout(Timeout, TimeoutLengthMs);
    });

    function Timeout() {
        GetGameState(steamId, GetGameStateUrl);
    }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>
}